Algoritmo "Exercicio_7"

Var

   Nota1:real
   Nota2:real
   Media:real

Inicio
      //Informação das Variáveis
      escreva("Informe a primeira nota do aluno: ")
      leia(Nota1)
      escreva("Informe a segunda nota do aluno: ")
      leia(Nota2)
      
      Media:= (Nota1 + Nota2) /2
      
      //Execução do programa
      escreva("A média semestral do aluno é: ",Media)


Fimalgoritmo