Algoritmo "Exercicio_3"

Var

   ValorTV:real

Inicio

      escreva("INSIRA O VALOR DA TELEVISÃO: ")
      leia(ValorTV)
      limpatela
      escreval("VALOR PARA PAGAMENTO À VISTA NO DINHIERO")
      escreval("R$",ValorTV)
      escreval()
      escreval("VALOR PARA PAGAMENTO NO CARTÃO DE CRÉDITO")
      escreval("JUROS DE 7%")
      escreval("VALOR DE JUROS EM R$: R$",ValorTV*0.07)
      escreval("VALOR FINAL: R$",ValorTV*1.07)


Fimalgoritmo