Algoritmo "Exercicio_7"

Var

   num, num2:inteiro

Inicio

   escreva("INSIRA O PRIMEIRO VALOR: ")
   leia(num)
   escreva("INSIRA O SEGUNDO VALOR: ")
   leia(num2)

   se(num>num2)entao
      escreva("O VALOR ",num," É MAIOR")
   fimse
   se(num2>num)entao
      escreva("O VALOR ",num2," É MAIOR")
   fimse
   se(num=num2)entao
      escreva("OS VALORES SÃO IGUAIS")
   fimse

Fimalgoritmo