Algoritmo "Exercicio_5"

Var

   num:real

Inicio

   escreva("INSIRA UM VALOR: ")
   leia(num)
   escreval()

   se(num>=100)entao
      se(num<=200)entao
      escreva(num," ESTÁ NO INTERVALO ENTRE 100 E 200")
      senao
      escreva(num," NÃO ESTÁ NO INTERVALO ENTRE 100 E 200")
      fimse
   senao
   escreva(num," NÃO ESTÁ NO INTERVALO ENTRE 100 E 200")
   fimse

Fimalgoritmo